global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'payments-api'
    metrics_path: '/api/v1/metrics/prometheus'
    static_configs:
      - targets: ['payments-api:80']
        labels:
          service: 'payments'

  - job_name: 'onboarding-api'
    metrics_path: '/health'
    static_configs:
      - targets: ['onboarding-api:80']
        labels:
          service: 'onboarding'

  - job_name: 'gateway'
    metrics_path: '/health'
    static_configs:
      - targets: ['gateway:80']
        labels:
          service: 'gateway'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
