global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
  - job_name: 'krt-payments-api'
    metrics_path: '/api/v1/metrics/prometheus'
    static_configs:
      - targets: ['payments-api:80']
        labels:
          service: 'payments'
          environment: 'production'

  - job_name: 'krt-onboarding-api'
    metrics_path: '/api/v1/metrics/prometheus'
    static_configs:
      - targets: ['onboarding-api:80']
        labels:
          service: 'onboarding'
          environment: 'production'

  - job_name: 'krt-gateway'
    metrics_path: '/api/v1/metrics/prometheus'
    static_configs:
      - targets: ['gateway:80']
        labels:
          service: 'gateway'
          environment: 'production'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']